apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo-system
  name: ucp-core
spec:
  project: ucp
  source:
    path: level1
    repoURL: https://github.com/mad01/argocd-example
    targetRevision: main
    helm:
      releaseName: level1
      valuesObject:
        targetRevision: main

  destination:
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
